### ISSUE TITLE
Create scheduled task to lock down private GDrive files

### ISSUE THREAD

**Issue by patcon** [hyphacoop/worker-coop-scripts#6]
Ticketed from [chat](https://matrix.to/#/!JloFJtoONurMdgcZCa:tomesh.net/$15701352712147zMiCp:tomesh.net)

## Shared Description

:speaking_head: **Loomio:** N/A  
:date: **Due date:** N/A  
:dart: **Success criteria:** We know that our private files will never be left open for more than X minutes.  

## To Do

- [ ] write script
- [ ] document in readme
- [ ] seek member feedback
- [ ] reference in handbook?
- [ ] set to run regularly via CircleCI

**Comment by benhylau** [comment]
I think we should stick with GDrive for now, and use a script, but I can see this being a slightly convoluted long term solution. I want to identify the GDrive features that we have not found elsewhere.

Are we using GDrive instead of **Nextcloud** only because of integrated Google Docs and Sheets, or are there other reasons?

**Cryptpad for Business** provides these but I think the user-level access control and Suggestion mode for doc edit are missing.

**Comment by patcon** [comment]
I'm def down to consider other tools, though yes, not priority imho. (We're likely in agreement that we've all used gdocs long enough to know what we value about it.)

>  I want to identify the GDrive features that we have not found elsewhere.

Feel free to start a place/doc/thread. Not sure this feels like the right spot to inventory that, but no objection to it being here

**Comment by garrying** [comment]
WONTDO
